server:
  port: 8083
spring:
  application:
    name: note
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/postgres?currentSchema=notes_schema
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  jackson:
    default-property-inclusion: non_null
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.yaml

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST}:8761/eureka


kafka:
  topic: notes
  partitions: 10
  replicas: 1
  port: ${KAFKA_HOST}:9092
  key: ${KAFKA_KEY}

open:
  feign:
    host: ${FEIGN_HOST}